"""create company state schema

Revision ID: f23fe45555a2
Revises: 
Create Date: 2026-09-18 20:46:59.670657

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f23fe45555a2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'COMPLETED', 'FAILED', name='simulationcyclestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('inventory', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('employees', sa.Integer(), nullable=False),
    sa.Column('market_share', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['simulation_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('previous_state_id', sa.Integer(), nullable=False),
    sa.Column('resulting_state_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['simulation_cycles.id'], ),
    sa.ForeignKeyConstraint(['previous_state_id'], ['company_states.id'], ),
    sa.ForeignKeyConstraint(['resulting_state_id'], ['company_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_transitions')
    op.drop_table('company_states')
    op.drop_table('simulation_cycles')
    op.drop_table('companies')
    # ### end Alembic commands ###
